language: node_js
node_js:
  - "8"

branches:
  only:
    - master

script:
  - ng build --prod --no-aot --base-href=/ngx-daterangepicker-material/

after_success:
  - ngh --dir demo/dist --repo=https://GH_TOKEN@github.com/fetrarij/ngx-daterangepicker-material.git

notifications:
  email:
    on_failure: change
    on_success: change