language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --no-aot --base-href=\"/ngx-daterangepicker-material/\"

after_success:
  - ngh --dir dist --repo=https://GH_TOKEN@github.com/fetrarij/ngx-daterangepicker-material.git

notifications:
  email:
    on_failure: change
    on_success: change